export const SET_MARKED = "SET_MARKED";
export const SET_STATS = 'SET_STATS';
export const SET_BARANGAY_DATA = 'SET_BARANGAY_DATA';
export const SET_REFRESHER = 'SET_REFRESHER';
export const SET_SELECTED_BARANGAY = "SET_SELECTED_BARANGAY";
export const SET_ADMIN_STATUS = "SET_ADMIN_STATUS";
