# Generated by Django 4.2.11 on 2024-05-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aim', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_order', models.PositiveIntegerField(blank=True, null=True)),
                ('house_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sitio', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('status_of_residency', models.CharField(blank=True, max_length=100, null=True)),
                ('length_of_stay', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_archieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('father_age', models.CharField(blank=True, max_length=10, null=True)),
                ('father_ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_religion', models.CharField(blank=True, max_length=100, null=True)),
                ('father_contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_age', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_religion', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('guardian_age', models.CharField(blank=True, max_length=10, null=True)),
                ('guardian_ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_religion', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_child_data.childinformation')),
            ],
        ),
        migrations.CreateModel(
            name='ChildHealthInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_weighing', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muac', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bpe', models.CharField(blank=True, max_length=20, null=True)),
                ('wfa', models.CharField(blank=True, max_length=100, null=True)),
                ('lfa', models.CharField(blank=True, max_length=100, null=True)),
                ('wfl', models.CharField(blank=True, max_length=100, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_child_data.childinformation')),
            ],
        ),
    ]
