# Generated by Django 4.2.11 on 2024-03-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='age',
            new_name='father_age',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='contact_number',
            new_name='father_contact_number',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='ethnicity',
            new_name='father_ethnicity',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='first_name',
            new_name='father_first_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='last_name',
            new_name='father_last_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='middle_name',
            new_name='father_middle_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='occupation',
            new_name='father_occupation',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='religion',
            new_name='father_religion',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='suffix',
            new_name='father_suffix',
        ),
        migrations.AddField(
            model_name='parent',
            name='guardian_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='guardian_contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='guardian_ethnicity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='guardian_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='guardian_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='guardian_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='guardian_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='guardian_religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='guardian_suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_ethnicity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ParentInformation',
        ),
    ]
