# Generated by Django 4.2.11 on 2024-03-30 09:53

import app_child_data.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0002_rename_age_parent_father_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinformation',
            name='date_of_birth',
            field=app_child_data.models.MMDDYYYYDateField(blank=True, null=True),
        ),
    ]
