# Generated by Django 4.2.11 on 2024-03-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0003_alter_childinformation_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinformation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
