# Generated by Django 4.2.11 on 2024-03-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0004_alter_childinformation_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childinformation',
            name='age',
        ),
    ]
