# Generated by Django 4.2.11 on 2024-03-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0005_remove_childinformation_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childhealthinformation',
            name='bpe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='childhealthinformation',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='childhealthinformation',
            name='muac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='childhealthinformation',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
