# Generated by Django 4.2.11 on 2024-03-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0006_alter_childhealthinformation_bpe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_child_data.childinformation'),
        ),
    ]
