# Generated by Django 4.2.11 on 2024-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0007_parent_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='guardian_age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
