# Generated by Django 4.2.11 on 2024-04-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0008_alter_parent_father_age_alter_parent_guardian_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childhealthinformation',
            name='lfa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinformation',
            name='wfa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinformation',
            name='wfl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='childinformation',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='childinformation',
            name='duration_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='childinformation',
            name='house_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='childinformation',
            name='length_of_stay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childinformation',
            name='sitio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='childinformation',
            name='status_of_residency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
