# Generated by Django 4.2.11 on 2024-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0009_childhealthinformation_lfa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinformation',
            name='aim',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
