# Generated by Django 4.2.11 on 2024-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0010_childinformation_aim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinformation',
            name='aim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
