# Generated by Django 4.2.11 on 2024-04-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_child_data', '0011_alter_childinformation_aim'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinformation',
            name='is_archieved',
            field=models.BooleanField(default=False),
        ),
    ]
