const InitialFormData = {
  last_name: '',
  first_name: '',
  middle_name: '',
  suffix: '',
  date_of_birth: '',
  gender: '',
  birth_weight: '',
  birth_order: '',

  house_number: '',
  sitio: '',
  barangay: '',
  status_of_residency: '',
  length_of_stay: '',
  duration_type: '',

  father_first_name: '',
  father_last_name: '',
  father_middle_name: '',
  father_suffix: '',
  father_age: '',
  father_ethnicity: '',
  father_occupation: '',
  father_religion: '',
  father_contact_number: '',

  mother_last_name: '',
  mother_first_name: '',
  mother_middle_name: '',
  mother_suffix: '',
  mother_age: '',
  mother_ethnicity: '',
  mother_occupation: '',
  mother_religion: '',
  mother_contact_number: '',

  guardian_first_name: '',
  guardian_last_name: '',
  guardian_middle_name: '',
  guardian_suffix: '',
  guardian_age: '',
  guardian_ethnicity: '',
  guardian_occupation: '',
  guardian_religion: '',
  guardian_contact_number: '',

  date_of_weighing: '',
  weight: '',
  height: '',
  muac: '',
  bpe: '',
  wfa: '',
  lfa: '',
  wfl: '',
  disability: ''
};

export default InitialFormData;
